#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Thu Apr 21 12:10:56 2005

# Papagayo-NG, a lip-sync tool for use with several different animation suites
# Original Copyright (C) 2005 Mike Clifton
# Contact information at http://www.lostmarble.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
import yaml
from pathlib import Path
from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtUiTools import QUiLoader as uic
from PySide6.QtCore import QFile

import path_utils


class AboutBox:
    def __init__(self):
        self.loader = None
        self.ui = None
        self.ui_file = None
        about_box_ui = path_utils.get_resource_path("rsrc", "about_box.ui")
        self.main_window = self.load_ui_widget(about_box_ui)
        icon_path = path_utils.get_resource_path("rsrc", "window_icon.bmp")
        self.main_window.setWindowIcon(QtGui.QIcon(str(icon_path)))
        self.main_window.about_ok_button.clicked.connect(self.close)
        self.main_window.license.anchorClicked.connect(self.open_license)
        self.main_window.license_version.setText(f"Version: {self.get_version_from_yaml()}")
        about_md = path_utils.get_file_inside_exe("about_markdown.html")
        self.markdown_url = QtCore.QUrl.fromLocalFile(str(about_md))
        self.main_window.license.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_window.license.setSource(self.markdown_url)

    def get_version_from_yaml(self):
        version_file = open(path_utils.get_file_inside_exe("version_information.txt"))
        version_data = yaml.safe_load(version_file)
        return version_data["Version"]

    def open_license(self, event):
        print(f"Clicked on {event.toString()}")
        if event.toString() == "rsrc/gpl.html":
            license_path = QtCore.QUrl.fromLocalFile(
                str(path_utils.get_resource_path("rsrc", "gpl.html"))
            )
            QtGui.QDesktopServices.openUrl(license_path)
        else:
            QtGui.QDesktopServices.openUrl(event)

    def load_ui_widget(self, ui_filename, parent=None):
        loader = uic()
        file = QFile(ui_filename)
        file.open(QFile.ReadOnly)
        self.ui = loader.load(file, parent)
        file.close()
        return self.ui

    def close(self):
        self.main_window.close()
# end of class AboutBox
