# -*- coding: ISO-8859-1|`
# generated by wxGlade 0.3.5.1 on Wed Apr 13 16:04:35 2005

# Papagayo-NG, a lip-sync tool for use with several different animation suites
# Original Copyright (C) 2005 Mike Clifton
# Contact information at http://www.lostmarble.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import importlib
import logging
import os
import sys
import time
from functools import partial

from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import QFile
from PySide6.QtUiTools import QUiLoader as uic

import path_utils
import utilities
from AboutBoxQT import AboutBox
from MouthViewQT import MouthView
from SettingsQT import SettingsWindow
from WaveformViewRewrite import WaveformView
import LipsyncDoc

app_title = "Papagayo-NG"
lipsync_extension_list = ("pgo", "pg2")
audio_extension_list = ("wav", "mp3", "aiff", "aif", "au", "snd", "mov", "m4a")
export_file_types = ("txt", "json", "dat")
exporter_list = ("MOHO", "ALELO", "Images", "JSON")
lipsync_extension = "".join(" *.{}".format(ext) for ext in lipsync_extension_list)[1:]
audio_extensions = "".join(" *.{}".format(ext) for ext in audio_extension_list)[1:]
open_wildcard = "{} and sound files ({} {})".format(app_title, audio_extensions, lipsync_extension)
save_wildcard = "{} files ({})".format(app_title, lipsync_extension)

# Recognizer names (used in menus, config, and checkbox state)
RECOGNIZER_ONNX = "ONNX"
RECOGNIZER_LIST = (RECOGNIZER_ONNX,)

# LipsyncObject object_type values
OBJECT_TYPE_VOICE = "voice"
OBJECT_TYPE_PHRASE = "phrase"
OBJECT_TYPE_WORD = "word"

DEFAULT_VOICE_NAME = "Voice 1"


class DropFilter(QtCore.QObject):
    def eventFilter(self, obj, event):
        if event.type() == QtCore.QEvent.Type.DragEnter:
            if event.mimeData().hasUrls():
                event.accept()
            else:
                event.ignore()
            return True
        elif event.type() == QtCore.QEvent.Type.Drop:
            if event.mimeData().hasUrls():
                # event.accept()
                for url in event.mimeData().urls():
                    if sys.platform == "darwin":
                        from Foundation import NSURL
                        fname = str(NSURL.URLWithString_(str(url.toString())).filePathURL().path())
                        obj.topLevelWidget().lip_sync_frame.open(fname)
                    else:
                        fname = str(url.toLocalFile())
                        obj.topLevelWidget().lip_sync_frame.open(fname)
                return True
            else:
                event.ignore()
                return False

        else:
            return False


class VoiceRecognitionThread(QtCore.QThread):
    """Runs phoneme recognition in a background thread to keep the UI responsive.

    Emits *progress_signal* with a status string during model loading and
    recognition, *finished_signal* with (doc, error_message) when done.
    """

    progress_signal = QtCore.Signal(str)
    finished_signal = QtCore.Signal(object, str)

    def __init__(self, parent, doc):
        super().__init__(parent)
        self.doc = doc
        self._is_running = False

    def stop(self):
        self._is_running = False

    def run(self):
        self._is_running = True
        error_msg = ""
        try:
            self.progress_signal.emit("Preparing voice...")
            if self.doc and self.doc.sound:
                if len(self.doc.project_node.children) < 1:
                    self.doc.current_voice = LipsyncDoc.LipSyncObject(
                        object_type=OBJECT_TYPE_VOICE, name=DEFAULT_VOICE_NAME,
                        parent=self.doc.project_node)
                else:
                    self.doc.current_voice.children = []

                self.progress_signal.emit("Loading model...")
                self.doc.auto_recognize_phoneme(manual_invoke=True)
                self.progress_signal.emit("Done")
        except Exception as e:
            logging.error(f"Voice recognition thread error: {e}")
            error_msg = str(e)

        if self._is_running:
            self.finished_signal.emit(self.doc, error_msg)


def sort_mouth_list_order(elem):
    try:
        return int(elem.split("-")[0])
    except ValueError:
        return hash(elem)


def open_file_no_gui(path, parent):
    importlib.reload(LipsyncDoc)  # This makes the CLI version work on the first try but is very hacky
    langman = LipsyncDoc.LanguageManager()
    langman.init_languages()
    from settings_manager import SettingsManager
    settings = SettingsManager.get_instance()
    doc = LipsyncDoc.LipsyncDoc(langman, parent)
    if any(path.endswith(ext) for ext in lipsync_extension_list):
        if path.endswith(lipsync_extension_list[0]):
            # open a lipsync project
            doc.open(path)
        elif path.endswith(lipsync_extension_list[1]):
            # open a json based lipsync project
            doc.open_json(path)
        if doc.sound is None:
            logging.info(f"Could not load Sound file: {doc.soundPath}")
            return None
    else:
        # open an audio file
        doc.fps = settings.get_fps()
        doc.open_audio(path)
        if doc.sound is None:
            doc = None
        else:
            if len(doc.project_node.children) < 1:
                doc.current_voice = LipsyncDoc.LipSyncObject(object_type=OBJECT_TYPE_VOICE, name=DEFAULT_VOICE_NAME,
                                                             parent=doc.project_node)
            elif not doc.current_voice:
                doc.current_voice = doc.project_node.children[0]
            doc.auto_recognize_phoneme()
    return doc


class LipsyncFrame:
    def __init__(self):

        self.app = QtCore.QCoreApplication.instance()
        self.translator = utilities.ApplicationTranslator()
        self.loader = None
        self.ui_file = None
        self.ui = None
        self.doc = None
        self.about_dlg = None
        self.settings_dlg = None
        self.ui_path = path_utils.get_resource_path("rsrc", "papagayo-ng2.ui")
        self.main_window = self.load_ui_widget(self.ui_path)
        self.main_window.setWindowTitle("%s" % app_title)
        self.main_window.lip_sync_frame = self
        from settings_manager import SettingsManager
        self.config = SettingsManager.get_instance()

        # Initialize default ONNX settings if not present
        onnx_model = self.config.get_onnx_model()
        if not onnx_model:
            self.config.set_onnx_model("steveway/wav2phoneme")
        
        # Handle emotion model setting
        emotion_model = self.config.get_onnx_emotion_model()
        if not emotion_model:
            self.config.set_onnx_emotion_model("steveway/wav2emotion")

        tree_style = r'''QTreeView::branch:has-siblings:!adjoins-item {
                             border-image: url(./rsrc/vline.png) 0;}               
                         QTreeView::branch:has-siblings:adjoins-item {
                             border-image: url(./rsrc/branch-more.png) 0;}
                         QTreeView::branch:!has-children:!has-siblings:adjoins-item {
                             border-image: url(./rsrc/branch-end.png) 0;}
                         QTreeView::branch:has-children:!has-siblings:closed,
                         QTreeView::branch:closed:has-children:has-siblings {
                                 border-image: none;
                                 image: url(./rsrc/branch-closed.png); }
                         QTreeView::branch:open:has-children:!has-siblings,
                         QTreeView::branch:open:has-children:has-siblings  {
                                 border-image: none;
                                 image: url(./rsrc/branch-open.png); }'''
        self.main_window.parent_tags.setStyleSheet(tree_style)

        # TODO: need a good description for this stuff
        mouth_list = list(self.main_window.mouth_view.mouths.keys())
        mouth_list.sort(key=sort_mouth_list_order)
        for mouth in mouth_list:
            self.main_window.mouth_choice.addItem(mouth)
        self.main_window.mouth_choice.setCurrentIndex(0)
        self.main_window.mouth_choice.current_mouth = self.main_window.mouth_choice.currentText()
        self.langman = LipsyncDoc.LanguageManager()
        self.langman.init_languages()
        language_list = list(self.langman.language_table.keys())
        language_list.sort()

        c = 0
        select = 0
        for language in language_list:
            self.main_window.language_choice.addItem(language)
            if language == "English":
                select = c
            c += 1
        self.main_window.language_choice.setCurrentIndex(select)

        # setup phonemeset initialisation here
        self.phonemeset = LipsyncDoc.PhonemeSet()
        for name in self.phonemeset.alternatives:
            self.main_window.phoneme_set.addItem(name)
        current_index = self.main_window.phoneme_set.findText(self.phonemeset.selected_set)
        self.main_window.phoneme_set.setCurrentIndex(current_index)

        c = 0
        select = 0
        for exporter in exporter_list:
            self.main_window.export_combo.addItem(exporter)
            if exporter == "MOHO":
                select = c
            c += 1
        self.main_window.export_combo.setCurrentIndex(select)
        self.app.aboutToQuit.connect(self.on_close)
        self.ignore_text_changes = False
        # This adds our statuses to the statusbar
        self.mainframe_statusbar_fields = [app_title, self.translator.translate("LipsyncFrame", "Stopped")]
        self.play_status = QtWidgets.QLabel()
        self.play_status.setText(self.mainframe_statusbar_fields[1])
        # An empty Label to add a separator
        self.sep_status = QtWidgets.QLabel()
        self.sep_status.setText(u"")
        self.main_window.statusbar.addPermanentWidget(self.sep_status)
        self.main_window.statusbar.addPermanentWidget(self.play_status)
        self.main_window.statusbar.showMessage(self.mainframe_statusbar_fields[0])
        self.status_progress = QtWidgets.QProgressBar()
        self.main_window.statusbar.addPermanentWidget(self.status_progress)
        self.status_progress.hide()
        # This is for the buttons to add and remove voices from the TabBar
        self.tab_widgets = QtWidgets.QWidget()
        self.tab_layout = QtWidgets.QHBoxLayout()
        self.tab_add_button = QtWidgets.QToolButton()
        self.tab_add_button.setText("+")
        self.tab_add_button.setIcon(QtGui.QIcon(QtGui.QPixmap(":/rsrc/icons/add-line.png")))
        self.tab_add_button.setToolTip(self.translator.translate("LipsyncFrame", "Add a new Voice."))
        self.tab_remove_button = QtWidgets.QToolButton()
        self.tab_remove_button.setText("-")
        self.tab_remove_button.setIcon(QtGui.QIcon(QtGui.QPixmap(":/rsrc/icons/delete-bin-line.png")))
        self.tab_remove_button.setToolTip(self.translator.translate("LipsyncFrame", "Delete Current Voice."))
        self.tab_layout.addWidget(self.tab_add_button)
        self.tab_layout.addWidget(self.tab_remove_button)
        self.tab_layout.setContentsMargins(0, 0, 0, 0)
        self.tab_layout.setSpacing(1)
        self.tab_widgets.setContentsMargins(0, 0, 0, 0)
        self.tab_widgets.setLayout(self.tab_layout)
        self.main_window.current_voice.setCornerWidget(self.tab_widgets)
        # Connect Events
        self.main_window.action_play.triggered.connect(self.on_play)
        self.main_window.action_stop.triggered.connect(self.on_stop)
        self.main_window.action_open.triggered.connect(self.on_open)
        self.main_window.action_save.triggered.connect(self.on_save)
        self.main_window.action_save_as.triggered.connect(self.on_save_as)
        self.main_window.action_zoom_in.triggered.connect(self.main_window.waveform_view.on_zoom_in)
        self.main_window.action_zoom_out.triggered.connect(self.main_window.waveform_view.on_zoom_out)
        self.main_window.action_reset_zoom.triggered.connect(self.main_window.waveform_view.on_zoom_reset)
        self.main_window.action_settings.triggered.connect(self.show_settings)
        self.main_window.action_select_as_current_set.triggered.connect(self.set_current_phoneme_set)
        self.main_window.reload_dict_button.clicked.connect(self.on_reload_dictionary)
        self.main_window.waveform_view.horizontalScrollBar().sliderMoved.connect(
            self.main_window.waveform_view.on_slider_change)
        self.main_window.action_help_topics.triggered.connect(self.on_help)
        self.main_window.action_about_papagayo_ng.triggered.connect(self.on_about)
        self.main_window.export_combo.currentIndexChanged.connect(self.on_export_choice)
        self.main_window.voice_name_input.textChanged.connect(self.on_voice_name)
        self.main_window.export_button.clicked.connect(self.on_voice_export)
        self.main_window.breakdown_button.clicked.connect(self.on_voice_breakdown)
        self.main_window.voice_recognition_button.clicked.connect(self.on_voice_recognize)
        self.main_window.choose_imageset_button.clicked.connect(self.on_voice_image_choose)
        self.main_window.mouth_choice.currentIndexChanged.connect(self.on_mouth_choice)
        self.main_window.volume_slider.valueChanged.connect(self.change_volume)
        self.main_window.text_edit.textChanged.connect(self.on_voice_text)
        self.main_window.apply_fps.clicked.connect(self.apply_changed_fps)
        self.main_window.spread_out.clicked.connect(self.spread_out)
        self.main_window.add_tag.clicked.connect(self.add_tag)
        self.main_window.tag_entry.returnPressed.connect(self.add_tag)
        self.main_window.remove_tag.clicked.connect(self.remove_tag)
        self.main_window.apply_voice_change.clicked.connect(self.change_voice_for_selection)
        self.tab_add_button.clicked.connect(self.on_new_voice)
        self.tab_remove_button.clicked.connect(self.on_del_voice)
        self.main_window.current_voice.tabBar().currentChanged.connect(self.on_sel_voice_tab)
        # Voice recognition button — only ONNX is supported now.
        # No dropdown menu needed; the button triggers recognition directly.
        self.onnx_select = None  # kept for _set_recognizer_checkboxes compat
        self._set_recognizer_checkboxes(self.config.get_recognizer())

        self.dropfilter = DropFilter()
        self.main_window.topLevelWidget().installEventFilter(self.dropfilter)

        self.change_stylesheet()
        self.cur_frame = 0
        self.timer = None
        self.wv_height = 1
        self.old_height = self.wv_height
        self.zoom_factor = 1
        self.scroll_position = 0
        self.did_resize = False
        self.wv_pen = QtGui.QPen(QtCore.Qt.GlobalColor.darkBlue)
        self.wv_brush = QtGui.QBrush(QtCore.Qt.GlobalColor.blue)
        self.start_time = time.time()
        self.start_time_for_fps_calc = time.time()
        self.threadpool = QtCore.QThreadPool.globalInstance()

    def show_error_dialog(self, error_message):
        dlg = QtWidgets.QMessageBox()
        dlg.setText(error_message)
        dlg.setWindowTitle(app_title)
        dlg.setWindowIcon(self.main_window.windowIcon())
        dlg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
        dlg.setDefaultButton(QtWidgets.QMessageBox.StandardButton.Ok)
        dlg.setIcon(QtWidgets.QMessageBox.Icon.Information)
        dlg.exec_()

    def change_stylesheet(self):
        style_file_path = str(self.config.get_qss_file_path())
        if style_file_path:
            with open(style_file_path, "r") as style_file:
                self.app.setStyleSheet(style_file.read())
        else:
            self.app.setStyleSheet("")

    def load_ui_widget(self, ui_filename, parent=None):
        self.loader = uic()
        file = QFile(ui_filename)
        file.open(QFile.ReadOnly)
        self.loader.registerCustomWidget(MouthView)
        self.loader.registerCustomWidget(WaveformView)
        self.ui = self.loader.load(file, parent)
        file.close()
        return self.ui

    def status_bar_progress(self, n):
        """Progress callback used by WaveformView and other workers."""
        self.status_progress.setValue(n)
        QtCore.QCoreApplication.processEvents()

    def set_current_phoneme_set(self, event=None):
        if self.doc:
            phonemeset_name = self.main_window.phoneme_set.currentText()
            self.phonemeset.selected_set = self.phonemeset.load(phonemeset_name)

    def _set_recognizer_checkboxes(self, recognizer_name):
        """No-op now that only ONNX is supported. Kept for compatibility."""
        pass

    def select_voice_recognizer(self, event=None):
        """No-op now that only ONNX is supported. Kept for compatibility."""
        pass

    def change_voice_for_selection(self):
        # TODO: We don't handle overlapping objects yet!
        selected_obj = self.main_window.waveform_view.currently_selected_object
        logging.debug("Currently Selected Object: %s", selected_obj.title)
        logging.debug("Corresponding LipsyncObject: %s", vars(selected_obj.node))
        logging.debug("Current Voice: %s", self.doc.current_voice.name)
        logging.debug("New Voice: %s", self.main_window.voice_for_selection.currentText())
        moving_object = selected_obj.node
        target_voice_name = self.main_window.voice_for_selection.currentText()
        new_voice_parent = next(
            (v for v in self.doc.project_node.children if v.name == target_voice_name), None)
        # Find existing parent object for selected one
        old_parent = moving_object.parent
        parent_instance = old_parent.object_type
        new_parent_object = None

        if parent_instance == OBJECT_TYPE_VOICE:
            moving_object.parent = new_voice_parent
        else:
            # Search for an existing phrase/word in the target voice that contains this object
            for possible_parent in new_voice_parent.children:
                if parent_instance == OBJECT_TYPE_PHRASE:
                    if possible_parent.start_frame <= moving_object.start_frame and possible_parent.end_frame >= moving_object.end_frame:
                        new_parent_object = possible_parent
                elif parent_instance == OBJECT_TYPE_WORD:
                    for possible_word_parent in possible_parent.children:
                        if possible_word_parent.start_frame <= moving_object.start_frame <= possible_word_parent.end_frame:
                            new_parent_object = possible_word_parent
            if new_parent_object:
                moving_object.parent = new_parent_object
            else:
                # No matching container found: create a new phrase (and word, if needed) under the target voice
                if parent_instance == OBJECT_TYPE_PHRASE:
                    new_temp_parent = LipsyncDoc.LipSyncObject(
                        object_type=OBJECT_TYPE_PHRASE, text=moving_object.text,
                        start_frame=moving_object.start_frame, end_frame=moving_object.end_frame,
                        parent=new_voice_parent, children=[moving_object])
                    moving_object.parent = new_temp_parent
                elif parent_instance == OBJECT_TYPE_WORD:
                    new_temp_parent = LipsyncDoc.LipSyncObject(
                        object_type=OBJECT_TYPE_PHRASE, text=moving_object.text,
                        start_frame=moving_object.start_frame, end_frame=moving_object.end_frame,
                        parent=new_voice_parent)
                    new_word_parent = LipsyncDoc.LipSyncObject(
                        object_type=OBJECT_TYPE_WORD, text=moving_object.text,
                        start_frame=moving_object.start_frame, end_frame=moving_object.end_frame,
                        parent=new_temp_parent, children=[moving_object])
                    moving_object.parent = new_word_parent

        # Clean up emptied containers left behind in the old voice
        if old_parent.object_type == OBJECT_TYPE_WORD:
            phrase_parent = old_parent.parent
            if not old_parent.children:
                old_parent.parent = None
            if not phrase_parent.children:
                phrase_parent.parent = None
        if old_parent.object_type == OBJECT_TYPE_PHRASE:
            if not old_parent.children:
                old_parent.parent = None
        self.main_window.waveform_view.set_document(self.doc, force=True, clear_scene=True)

    def _sync_tags_from_widget(self):
        """Push the current contents of the tag list widget into the selected object's tags."""
        tags = [self.main_window.list_of_tags.item(i).text()
                for i in range(self.main_window.list_of_tags.count())]
        self.main_window.waveform_view.currently_selected_object.set_tags(tags)

    def add_tag(self):
        if self.main_window.tag_entry.text():
            self.main_window.list_of_tags.addItem(self.main_window.tag_entry.text())
            self.main_window.tag_entry.clear()
            self._sync_tags_from_widget()

    def remove_tag(self):
        self.main_window.list_of_tags.takeItem(self.main_window.list_of_tags.currentRow())
        self._sync_tags_from_widget()

    def spread_out(self):
        wfv = self.main_window.waveform_view
        top_nodes = self.doc.current_voice.children
        num_frames = wfv.waveform_polygon.polygon().boundingRect().width() / wfv.frame_width
        frames_per_top_level = num_frames / len(top_nodes)
        for num, top_node in enumerate(top_nodes):
            top_node.start_frame = round((num * frames_per_top_level) + int(bool(num)))
            top_node.end_frame = round((num * frames_per_top_level) + frames_per_top_level)
            top_node.move_button.after_reposition()
            top_node.move_button.reposition_descendants2(True)

    def apply_changed_fps(self):
        new_fps_value = self.main_window.fps_input.value()
        logging.info('FPS changed to: {0}'.format(str(new_fps_value)))
        old_fps_value = self.doc.fps
        resize_multiplier = new_fps_value / old_fps_value
        if resize_multiplier != 1:
            self.doc.fps = new_fps_value
            for l_object in self.doc.project_node.descendants:
                l_object.fps = new_fps_value
            wfv = self.main_window.waveform_view
            wfv.samples_per_sec = self.doc.fps * wfv.samples_per_frame
            wfv.start_recalc(True)
            wfv.scene().setSceneRect(wfv.scene().sceneRect().x(), wfv.scene().sceneRect().y(),
                                     wfv.sceneRect().width() * resize_multiplier, wfv.scene().sceneRect().height())
            wfv.setSceneRect(wfv.scene().sceneRect())
            wfv.scroll_position = 0
            wfv.horizontalScrollBar().setValue(wfv.scroll_position)
            self.doc.project_node.sound_duration = int(self.doc.sound.Duration() * self.doc.fps)
            self.doc.sound.change_fps(new_fps_value)

    def on_voice_recognize(self):
        if self.doc and self.doc.sound:
            # Disable the button while recognition is running.
            self.main_window.voice_recognition_button.setEnabled(False)
            self.main_window.voice_recognition_button.setText("Recognizing...")

            # Show the status progress bar in indeterminate mode.
            self.status_progress.show()
            self.status_progress.setRange(0, 0)  # indeterminate / busy indicator

            # Run recognition in a background thread.
            self._recognition_thread = VoiceRecognitionThread(
                self.main_window, self.doc)
            self._recognition_thread.progress_signal.connect(
                self._on_recognition_progress, QtCore.Qt.QueuedConnection)
            self._recognition_thread.finished_signal.connect(
                self._on_recognition_finished, QtCore.Qt.QueuedConnection)
            self._recognition_thread.start()

    def _on_recognition_progress(self, message):
        """Update the status bar with progress messages from the recognition thread."""
        self.main_window.statusbar.showMessage(message)
        QtCore.QCoreApplication.processEvents()

    def _on_recognition_finished(self, doc, error_msg):
        """Called when the background recognition thread completes."""
        self.status_progress.hide()
        self.main_window.voice_recognition_button.setEnabled(True)
        self.main_window.voice_recognition_button.setText("Voice Recognition")

        if error_msg:
            self.main_window.statusbar.showMessage(f"Recognition failed: {error_msg}", 5000)
            logging.error(f"Recognition failed: {error_msg}")
        else:
            self.main_window.statusbar.showMessage("Recognition complete.", 3000)

        # Refresh the views with the recognized data.
        self.main_window.waveform_view.set_document(self.doc, force=True, clear_scene=True)
        self.main_window.mouth_view.set_document(self.doc)

    def close_doc_ok(self):
        if self.doc is not None:
            if not self.doc.dirty:
                return True
            dlg = QtWidgets.QMessageBox()
            dlg.setText("Save changes to this project?")
            dlg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No)
            dlg.setDefaultButton(QtWidgets.QMessageBox.StandardButton.Yes)
            dlg.setIcon(QtWidgets.QMessageBox.Icon.Question)
            result = dlg.exec_()
            if result == QtWidgets.QMessageBox.StandardButton.Yes:
                self.on_save()
                if not self.doc.dirty:
                    self.config.set_fps(str(self.doc.fps))
                    return True
                else:
                    return False
            elif result == QtWidgets.QMessageBox.StandardButton.No:
                self.config.set_fps(str(self.doc.fps))
                return True
        else:
            return True

    def on_open(self):
        if not self.close_doc_ok():
            return
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(self.main_window,
                                                             "Open Audio or {} File".format(app_title),
                                                             str(self.config.get("WorkingDir",
                                                                                   utilities.get_main_dir())),
                                                             open_wildcard)
        if file_path:
            self.config.set("WorkingDir", os.path.dirname(file_path))
            self.open(file_path)

    def _open_lipsync_project(self, path):
        """Open a .pgo/.pg2 project, prompting for audio if the referenced file is missing."""
        if path.endswith(lipsync_extension_list[0]):
            self.doc.open(path)
        elif path.endswith(lipsync_extension_list[1]):
            self.doc.open_json(path)
        while self.doc.sound is None:
            # if no sound file found, then ask user to specify one
            dlg = QtWidgets.QMessageBox(self.main_window)
            dlg.setText('Please load correct audio file')
            dlg.setWindowTitle(app_title)
            dlg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            dlg.exec_()  # This should open it as a modal blocking window
            file_path = QtWidgets.QFileDialog.getOpenFileName(
                self.main_window, "Open Audio",
                str(self.config.get("WorkingDir", utilities.get_main_dir())),
                audio_extensions)[0]
            if file_path:
                self.doc.open_audio(file_path)

    def _open_audio_file(self, path):
        """Open an audio file, create a default voice, run recognition, and load any .trans file."""
        self.doc.fps = self.config.get_fps()
        self.doc.open_audio(path)
        if self.doc.sound is None:
            self.doc = None
            return
        if len(self.doc.project_node.children) < 1:
            self.doc.current_voice = LipsyncDoc.LipSyncObject(
                object_type=OBJECT_TYPE_VOICE, name=DEFAULT_VOICE_NAME, parent=self.doc.project_node)
        elif not self.doc.current_voice:
            self.doc.current_voice = self.doc.project_node.children[0]
        # Run recognition in the background to avoid freezing the UI.
        self.on_voice_recognize()
        # check for a .trans file with the same name as the doc
        try:
            with open("{}.trans".format(path.rsplit('.', 1)[0]), 'r') as txt_file:  # TODO: Check if path is correct
                for line in txt_file:
                    self.main_window.current_voice.tabBar().addTab(line.strip())
        except OSError:
            pass

    def _post_load_setup(self, path):
        """Wire up the UI after a document has been successfully loaded."""
        mw = self.main_window
        mw.setWindowTitle("{} [{}] - {}".format(self.doc.name, path, app_title))
        mw.waveform_view.first_update = True
        mw.waveform_view.set_document(self.doc, force=True, clear_scene=True)
        mw.mouth_view.set_document(self.doc)
        # Reenable all disabled widgets
        self._set_doc_widgets_enabled(True)
        mw.volume_slider.setValue(self.config.get_int("volume", 50))
        mw.action_cut.setEnabled(True)
        mw.action_cut.triggered.connect(self.on_del_object)
        mw.choose_imageset_button.setEnabled(False)
        mw.action_convert_phonemes.triggered.connect(self.doc.convert_to_phonemeset)
        if self.doc.sound is None:
            # No sound: disable playback/zoom again (overriding the helper)
            mw.action_play.setEnabled(False)
            mw.action_stop.setEnabled(False)
            mw.action_zoom_in.setEnabled(False)
            mw.action_zoom_out.setEnabled(False)
            mw.action_reset_zoom.setEnabled(False)
        mw.tag_list_group.setEnabled(False)
        list_of_voices = [voice.name for voice in self.doc.project_node.children]
        mw.voice_for_selection.clear()
        mw.voice_for_selection.addItems(list_of_voices)
        mw.phoneme_set.setCurrentIndex(mw.phoneme_set.findText(self.phonemeset.selected_set))

        first_entry = True
        for voice in self.doc.project_node.children:
            if not first_entry:
                mw.current_voice.tabBar().addTab(voice.name)
            else:
                mw.current_voice.tabBar().setTabText(0, voice.name)
                first_entry = False
        mw.fps_input.setValue(self.doc.fps)
        mw.voice_name_input.setText(self.doc.current_voice.name)
        mw.text_edit.setText(self.doc.current_voice.text)

        # reload dictionary
        self.on_reload_dictionary()
        self.doc.dirty = False

    def open(self, path):
        while self.main_window.current_voice.tabBar().count() > 1:
            self.main_window.current_voice.tabBar().removeTab(self.main_window.current_voice.tabBar().count() - 1)
        self.doc = LipsyncDoc.LipsyncDoc(self.langman, self)
        if any(path.endswith(ext) for ext in lipsync_extension_list):
            self._open_lipsync_project(path)
        else:
            self._open_audio_file(path)
        if self.doc is not None:
            self._post_load_setup(path)

    def on_save(self):
        if self.doc is None:
            return
        if self.doc.path is None:
            self.on_save_as()
            return
        if self.doc.path.endswith(lipsync_extension_list[0]):
            self.doc.save(self.doc.path)
        elif self.doc.path.endswith(lipsync_extension_list[1]):
            self.doc.save2(self.doc.path)

    def on_save_as(self):
        if self.doc is None:
            return
        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(self.main_window,
                                                             "Save {} File".format(app_title),
                                                             str(self.config.get("WorkingDir",
                                                                                 utilities.get_main_dir())),
                                                             save_wildcard)
        if file_path:
            self.config.set("WorkingDir", os.path.dirname(file_path))
            if file_path.endswith(lipsync_extension_list[0]):
                self.doc.save(file_path)
            elif file_path.endswith(lipsync_extension_list[1]):
                self.doc.save2(file_path)
            self.main_window.setWindowTitle("{} [{}] - {}".format(self.doc.name, file_path, app_title))

    def _set_doc_widgets_enabled(self, enabled):
        """Toggle the common set of widgets that depend on a loaded document."""
        mw = self.main_window
        mw.vertical_layout_right.setEnabled(enabled)
        mw.vertical_layout_left.setEnabled(enabled)
        mw.volume_slider.setEnabled(enabled)
        mw.action_save.setEnabled(enabled)
        mw.action_save_as.setEnabled(enabled)
        mw.menu_edit.setEnabled(enabled)
        mw.action_play.setEnabled(enabled)
        mw.action_stop.setEnabled(enabled)
        mw.action_zoom_in.setEnabled(enabled)
        mw.action_zoom_out.setEnabled(enabled)
        mw.action_reset_zoom.setEnabled(enabled)

    def on_close(self):
        if self.doc is not None:
            self.close_doc_ok()
            self.config.set_fps(str(self.doc.fps))
            del self.doc
        self.doc = None
        self.main_window.waveform_view.first_update = True
        self.main_window.waveform_view.set_document(self.doc)
        # clear voice controls
        self.main_window.voice_name_input.clear()
        self.main_window.text_edit.clear()
        self.main_window.fps_input.clear()
        self._set_doc_widgets_enabled(False)

    def on_quit(self, event=None):
        self.on_close()
        self.main_window.close()

    def on_help(self, event=None):
        github_path = "https://github.com/morevnaproject/papagayo-ng/issues"
        QtGui.QDesktopServices.openUrl(github_path)

    def on_about(self, event=None):
        self.about_dlg = AboutBox()
        self.about_dlg.main_window.show()

    def show_settings(self, event=None):
        self.settings_dlg = SettingsWindow(None, self.status_progress)
        self.settings_dlg.main_window.show()
        self.settings_dlg.main_window.finished.connect(self.settings_closed)

    def settings_closed(self):
        self.main_window.waveform_view.set_document(self.doc, True, True)
        self._set_recognizer_checkboxes(self.config.get_recognizer())
        self.change_stylesheet()

    def on_play(self, event=None):
        if (self.doc is not None) and (self.doc.sound is not None):
            self.cur_frame = -1
            self.main_window.action_play.setEnabled(False)
            self.main_window.action_stop.setEnabled(True)
            self.doc.sound.set_cur_time(0)
            self.doc.sound.play(False)
            # self.doc.sound.play_segment(0, self.doc.sound.Duration())
            self.timer = QtCore.QTimer()
            self.main_window.waveform_view.temp_play_marker.setVisible(True)
            self.timer.timeout.connect(self.on_play_tick)
            # self.connect(self.timer, None, self.on_play_tick)
            self.start_time = time.time()
            self.timer.start(1000.0 / self.doc.fps)

            # self.doc.sound.audio.positionChanged.connect(self.move_marker_callback)

    def on_stop(self, event=None):
        if (self.doc is not None) and (self.doc.sound is not None):
            self.doc.sound.stop()
            self.doc.sound.set_cur_time(0)
            self.main_window.waveform_view.temp_play_marker.setVisible(False)
            self.main_window.mouth_view.set_frame(0)
            self.main_window.waveform_view.set_frame(0)
            self.main_window.action_stop.setEnabled(False)
            self.main_window.action_play.setEnabled(True)
            self.main_window.statusbar.showMessage(self.translator.translate("LipsyncFrame", "Stopped"))
            self.main_window.waveform_view.horizontalScrollBar().setValue(
                self.main_window.waveform_view.scroll_position)
            self.main_window.waveform_view.update()
            QtCore.QCoreApplication.processEvents()

    def _update_playback_frame(self, cur_frame, fps_reference_time):
        """If `cur_frame` changed, advance the mouth/waveform views and update the status bar FPS readout."""
        if self.cur_frame == cur_frame:
            return
        self.cur_frame = cur_frame
        self.main_window.mouth_view.set_frame(self.cur_frame)
        self.main_window.waveform_view.set_frame(self.cur_frame)
        try:
            fps = 1.0 / (time.time() - fps_reference_time)
        except ZeroDivisionError:
            fps = 60
        self.main_window.statusbar.showMessage(self.translator.translate(
            "LipsyncFrame", "Frame: {:d} FPS: {:d}".format((cur_frame + 1), int(fps))))
        self.main_window.waveform_view.scroll_position = self.main_window.waveform_view.horizontalScrollBar().value()

    def on_play_tick(self, event=None):
        if (self.doc is not None) and (self.doc.sound is not None):
            if self.doc.sound.is_playing():
                cur_frame = int(self.doc.sound.current_time() * self.doc.fps)
                calculated_frame = round((time.time() - self.start_time) * self.doc.fps)
                if calculated_frame > cur_frame:
                    cur_frame = calculated_frame
                self._update_playback_frame(cur_frame, self.start_time_for_fps_calc)
                self.start_time_for_fps_calc = time.time()
            else:
                self.main_window.waveform_view.temp_play_marker.setVisible(False)
                self.on_stop()
                self.timer.stop()
                del self.timer

    def move_marker_callback(self, position):
        cur_frame = position // self.doc.fps
        logging.debug("Current Position: %s, Frame Position: %s", position, cur_frame)
        calculated_time = time.time() - self.start_time
        calculated_frame = round(calculated_time * self.doc.fps)
        logging.debug("Calculated Time: %s, Calculated Frame: %s", calculated_time, calculated_frame)
        if calculated_frame > cur_frame:
            cur_frame = calculated_frame
        self._update_playback_frame(cur_frame, self.start_time)

    def change_volume(self, e):
        if self.doc and self.doc.sound:
            self.doc.sound.set_volume(int(self.main_window.volume_slider.value()))
            self.config.set("volume", int(self.main_window.volume_slider.value()))

    def on_mouth_choice(self, event=None):
        self.main_window.mouth_view.current_mouth = self.main_window.mouth_choice.currentText()
        self.main_window.mouth_view.draw_me()

    def on_export_choice(self, event=None):
        if self.main_window.export_combo.currentText() == "Images":
            self.main_window.choose_imageset_button.setEnabled(True)
        else:
            self.main_window.choose_imageset_button.setEnabled(False)

    def on_voice_name(self, event=None):

        if (self.doc is not None) and (self.doc.current_voice is not None):
            self.doc.dirty = True
            self.doc.current_voice.name = self.main_window.voice_name_input.text()
            self.main_window.voice_name_input.setText(self.doc.current_voice.name)
            self.main_window.current_voice.tabBar().setTabText(self.main_window.current_voice.tabBar().currentIndex(),
                                                               self.doc.current_voice.name)
            self.main_window.waveform_view.first_update = True
            self.main_window.waveform_view.set_document(self.doc)

    def on_voice_text(self, event=None):
        if self.ignore_text_changes:
            return
        if (self.doc is not None) and (self.doc.current_voice is not None):
            self.doc.dirty = True
            self.doc.current_voice.text = self.main_window.text_edit.toPlainText()

    def on_voice_breakdown(self, event=None):
        if (self.doc is not None) and (self.doc.current_voice is not None):
            if not self.doc.current_voice.text.strip():
                self.show_error_dialog(
                    self.translator.translate("LipsyncFrame", "Please enter some text to break down."))
                return
            language = self.main_window.language_choice.currentText()
            phonemeset_name = self.main_window.phoneme_set.currentText()
            old_doc = self.doc.copy_to_dict()
            self.doc.dirty = True
            self.doc.current_voice.children = []
            return_value = self.doc.current_voice.run_breakdown(self.doc.soundDuration, self, language, self.langman,
                                                                self.phonemeset)
            if return_value == -1:
                self.doc.open_from_dict(old_doc)
            self.phonemeset.selected_set = self.phonemeset.load(phonemeset_name)
            self.main_window.waveform_view.first_update = True
            self.ignore_text_changes = True
            self.main_window.text_edit.setText(self.doc.current_voice.text)
            self.ignore_text_changes = False
            self.main_window.waveform_view.set_document(self.doc, True, True)

    # Per-exporter configuration: message/wildcard translation keys, default file
    # extension, an optional pre-check (returning False aborts), and the dispatch
    # callable that performs the actual export given (file_path, rest_frames).
    _EXPORTER_CONFIG = {
        "MOHO": {
            "message_key": "Export Lipsync Data (MOHO)",
            "default_ext": ".dat",
            "wildcard_key": "Moho switch files (*.dat)",
            "export": lambda self, fp, rest: self.doc.current_voice.export(
                fp if ("." in fp) else fp + ".dat", rest),
        },
        "ALELO": {
            "message_key": "Export Lipsync Data (ALELO)",
            "default_ext": ".txt",
            "wildcard_key": "Alelo timing files (*.txt)|*.txt",
            "pre_check": "_alelo_fps_check",
            "export": lambda self, fp, rest: self.doc.current_voice.export_alelo(
                fp, self._export_language, self.langman, rest),
        },
        "Images": {
            "message_key": "Export Image Strip",
            "default_ext": "",
            "wildcard_key": None,
            "export": lambda self, fp, rest: self.doc.current_voice.export_images(
                fp, self.main_window.mouth_choice.currentText(), rest),
        },
        "JSON": {
            "message_key": "Export JSON Object",
            "default_ext": ".json",
            "wildcard_key": "JSON object files (*.json)|*.json",
            "export": lambda self, fp, rest: self.doc.current_voice.export_json(
                fp, self.doc.soundPath, rest),
        },
    }

    def _alelo_fps_check(self):
        """ALELO expects 100 fps; warn and confirm before exporting at another rate."""
        if self.config.get_fps() == 100:
            return True
        dlg = QtWidgets.QMessageBox()
        dlg.setText(self.translator.translate(
            "LipsyncFrame", "FPS is NOT 100 continue? (You will have issues downstream.)"))
        dlg.setStandardButtons(
            QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No)
        dlg.setDefaultButton(QtWidgets.QMessageBox.StandardButton.Yes)
        dlg.setIcon(QtWidgets.QMessageBox.Icon.Question)
        return dlg.exec_() == QtWidgets.QMessageBox.StandardButton.Yes

    def on_voice_export(self, event=None):
        if self.doc is None or self.doc.current_voice is None:
            return
        exporter = self.main_window.export_combo.currentText()
        cfg = self._EXPORTER_CONFIG.get(exporter)
        if cfg is None:
            return
        # ALELO needs the current language for its export call; stash it on self
        # so the lambda in _EXPORTER_CONFIG can reach it without extra plumbing.
        self._export_language = self.main_window.language_choice.currentText()

        if "pre_check" in cfg and not getattr(self, cfg["pre_check"])():
            return

        message = self.translator.translate("LipsyncFrame", cfg["message_key"])
        default_file = "{}{}".format(self.doc.soundPath.rsplit('.', 1)[0], cfg["default_ext"])
        wildcard = (self.translator.translate("LipsyncFrame", cfg["wildcard_key"])
                    if cfg["wildcard_key"] else "")

        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
            self.main_window, message, default_file, wildcard,
            options=QtWidgets.QFileDialog.Option.DontUseNativeDialog)
        if not file_path:
            return
        self.config.set("WorkingDir", os.path.dirname(file_path))
        cfg["export"](self, file_path, self.main_window.apply_rest_frames_on_export.isChecked())

    def on_sel_voice_tab(self, e):
        if not self.doc:
            return
        prev_dirty = self.doc.dirty
        self.ignore_text_changes = True
        for voice in self.doc.project_node.children:
            if voice.name == self.main_window.current_voice.tabBar().tabText(
                    self.main_window.current_voice.tabBar().currentIndex()):
                self.doc.current_voice = voice

        self.main_window.list_of_tags.clear()
        self.main_window.tag_list_group.setEnabled(False)
        self.main_window.voice_name_input.setText(self.doc.current_voice.name)
        self.main_window.text_edit.setText(self.doc.current_voice.text)
        self.ignore_text_changes = False
        self.main_window.voice_for_selection.setCurrentIndex(self.main_window.current_voice.tabBar().currentIndex())
        self.main_window.waveform_view.set_document(self.doc, True)
        self.main_window.mouth_view.draw_me()
        self.doc.dirty = prev_dirty

    def on_new_voice(self, event=None):
        if not self.doc:
            return
        self.doc.dirty = True
        voice_exist_count = 1
        new_voice_name = "Voice {:d}".format(len(self.doc.project_node.children) + voice_exist_count)
        voice_name_exists = True
        while voice_name_exists:
            voice_name_exists = False
            new_voice_name = "Voice {:d}".format(len(self.doc.project_node.children) + voice_exist_count)
            for voice in self.doc.project_node.children:
                if voice.name == new_voice_name:
                    voice_name_exists = True
                    voice_exist_count += 1
                    break

        self.doc.current_voice = LipsyncDoc.LipSyncObject(object_type=OBJECT_TYPE_VOICE, name=new_voice_name,
                                                          parent=self.doc.project_node)
        self.main_window.current_voice.tabBar().addTab(self.doc.current_voice.name)
        self.main_window.current_voice.tabBar().setCurrentIndex(self.main_window.current_voice.tabBar().count() - 1)
        self.ignore_text_changes = True
        self.main_window.voice_name_input.setText(self.doc.current_voice.name)
        self.main_window.text_edit.setText(self.doc.current_voice.text)
        self.ignore_text_changes = False
        list_of_voices = [voice.name for voice in self.doc.project_node.children]
        self.main_window.voice_for_selection.clear()
        self.main_window.voice_for_selection.addItems(list_of_voices)
        self.main_window.voice_for_selection.setCurrentIndex(self.main_window.current_voice.tabBar().count() - 1)
        self.main_window.waveform_view.set_document(self.doc, True)
        self.main_window.mouth_view.draw_me()

    def on_del_object(self):
        self.main_window.waveform_view.currently_selected_object.node.parent = None
        all_delete_items = []
        all_delete_items.extend(self.main_window.waveform_view.currently_selected_object.node.descendants)
        all_delete_items.append(self.main_window.waveform_view.currently_selected_object.node)
        for item in self.main_window.waveform_view.scene().items():
            if isinstance(item, QtWidgets.QGraphicsProxyWidget):
                for to_delete in all_delete_items:
                    if item.widget() == to_delete.move_button:
                        self.main_window.waveform_view.scene().removeItem(item)
        del self.main_window.waveform_view.currently_selected_object.node

    def on_del_voice(self, event=None):
        if (not self.doc) or (len(self.doc.project_node.children) == 1):
            return
        self.doc.dirty = True
        new_index = self.doc.project_node.children.index(self.doc.current_voice)
        if new_index > 0:
            new_index -= 1
        else:
            new_index = 0
        self.doc.current_voice.parent = None
        del self.doc.current_voice
        self.doc.current_voice = self.doc.project_node.children[new_index]
        self.main_window.voice_name_input.setText(self.doc.current_voice.name)
        self.main_window.text_edit.setText(self.doc.current_voice.text)
        self.main_window.current_voice.tabBar().removeTab(self.main_window.current_voice.tabBar().currentIndex())
        list_of_voices = [voice.name for voice in self.doc.project_node.children]
        self.main_window.voice_for_selection.clear()
        self.main_window.voice_for_selection.addItems(list_of_voices)
        self.main_window.voice_for_selection.setCurrentIndex(new_index)
        self.main_window.waveform_view.set_document(self.doc, True, True)
        self.main_window.mouth_view.draw_me()

    def on_voice_image_choose(self, event=None):
        language = self.main_window.language_choice.currentText()
        if (self.doc is not None) and (self.doc.current_voice is not None):
            voiceimage_path = QtWidgets.QFileDialog.getExistingDirectory(self.main_window,
                                                                         self.translator.translate("LipsyncFrame",
                                                                                                   "Choose Path for Images"),
                                                                         str(self.config.get("MouthDir",
                                                                                               os.path.join(
                                                                                                   os.path.dirname(
                                                                                                       os.path.abspath(
                                                                                                           __file__)),
                                                                                                   "rsrc",
                                                                                                   r"mouths/"))))
            if voiceimage_path:
                self.config.set_mouth_dir(voiceimage_path)
                supported_imagetypes = QtGui.QImageReader.supportedImageFormats()
                for directory, dir_names, file_names in os.walk(voiceimage_path):
                    self.main_window.mouth_view.process_mouth_dir(directory, file_names, supported_imagetypes)
                mouth_list = list(self.main_window.mouth_view.mouths.keys())
                mouth_list.sort(key=sort_mouth_list_order)
                self.main_window.mouth_choice.clear()
                for mouth in mouth_list:
                    self.main_window.mouth_choice.addItem(mouth)
                self.main_window.mouth_choice.setCurrentIndex(
                    self.main_window.mouth_choice.findText(os.path.basename(voiceimage_path)))
                self.main_window.mouth_view.current_mouth = self.main_window.mouth_choice.currentText()

    def on_reload_dictionary(self, event=None):
        logging.info("reload the dictionary")
        lang_config = self.doc.language_manager.language_table[self.main_window.language_choice.currentText()]
        self.doc.language_manager.load_language(lang_config, force=True)

# end of class LipsyncFrame
