#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Thu Apr 21 12:10:56 2005

# Papagayo-NG, a lip-sync tool for use with several different animation suites
# Original Copyright (C) 2005 Mike Clifton
# Contact information at http://www.lostmarble.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
import os
from functools import partial

import PySide6.QtWidgets as QtWidgets
from PySide6 import QtCore, QtGui
from PySide6.QtCore import QFile, QThread, QObject, Signal, Qt
from PySide6.QtUiTools import QUiLoader as uic

import path_utils
import utilities
from settings_manager import SettingsManager


class MySignal(QObject):
    sig = Signal(str)


class ProgressSignal(QObject):
    progress = Signal(int)


class OnnxDownloadThread(QThread):
    """Downloads an ONNX model via the phonemation_backend REST API.

    Runs in a background thread so the UI stays responsive.  Progress
    is reported via *progress_signal* (0..100 int) and completion via
    *finished_signal* (message string).
    """

    progress_signal = Signal(int)
    finished_signal = Signal(str)

    def __init__(self, parent, model_name, model_path=""):
        super().__init__(parent)
        self.model_name = model_name
        self.model_path = model_path  # kept for interface compat, unused
        self._is_running = False

    def change_name_and_path(self, model_name, model_path):
        self.model_name = model_name
        self.model_path = model_path

    def stop(self):
        print("Stopping download thread...")
        self._is_running = False
        if self.isRunning():
            self.terminate()
            self.wait()

    def run(self):
        self._is_running = True
        try:
            from backend_recognizer import BackendRecognizer

            recognizer = BackendRecognizer()
            if not self._is_running:
                return

            def on_progress(percent):
                if self._is_running:
                    self.progress_signal.emit(int(percent))

            path = recognizer.download_model(self.model_name,
                                             progress_callback=on_progress)
            if self._is_running:
                if path:
                    self.finished_signal.emit("Download complete")
                else:
                    self.finished_signal.emit("Download failed")
        except Exception as e:
            print(f"Download error: {str(e)}")
            if self._is_running:
                self.finished_signal.emit(f"Download failed: {str(e)}")
        finally:
            self._is_running = False

class SettingsWindow:
    def __init__(self, progress_callback, status_bar_progress):
        self.progress_callback = progress_callback
        self.status_bar_progress = status_bar_progress
        self.ui_path = path_utils.get_resource_path("rsrc", "settings.ui")
        self.main_window = self.load_ui_widget(self.ui_path)
        self.settings_manager = SettingsManager.get_instance()

        # Initialize download thread after main window is created
        self.download_thread = OnnxDownloadThread(self.main_window, "", "")
        self.download_thread.progress_signal.connect(self.update_progress, Qt.QueuedConnection)
        self.download_thread.finished_signal.connect(self.onnx_complete, Qt.QueuedConnection)

        self.init_ui()

    def load_ui_widget(self, ui_filename, parent=None):
        loader = uic()
        file = QFile(ui_filename)
        file.open(QFile.ReadOnly)
        self.ui = loader.load(file, parent)
        file.close()
        return self.ui

    def download_onnx_model(self):
        # Strip the download-status mark to get the raw model id.
        model_name = self.main_window.available_onnx_models.currentText()
        model_name = model_name.replace("[v] ", "").replace("[ ] ", "")
        self.status_bar_progress.show()
        self.status_bar_progress.setMaximum(100)
        self.status_bar_progress.setMinimum(0)
        self.status_bar_progress.setValue(0)
        self.download_thread.change_name_and_path(model_name, "")
        self.download_thread.start()

    def onnx_complete(self, data):
        print(f"Download finished with message: {data}")
        self.status_bar_progress.hide()
        # Refresh the model list so the downloaded status updates.
        self._refresh_onnx_model_list()

    def _refresh_onnx_model_list(self):
        """Re-populate the ONNX model dropdown with current download status."""
        try:
            from backend_recognizer import BackendRecognizer
            recognizer = BackendRecognizer()
            models = recognizer.list_models("phoneme")
        except Exception as e:
            print(f"Could not refresh ONNX model list: {e}")
            return

        self._onnx_models = models
        # Remember the current selection (by model id).
        current_id = self.main_window.available_onnx_models.currentText()
        current_id = current_id.replace("[v] ", "").replace("[ ] ", "")

        self.main_window.available_onnx_models.clear()
        select_index = 0
        for i, m in enumerate(models):
            mark = "[v] " if m["downloaded"] else "[ ] "
            self.main_window.available_onnx_models.addItem(mark + m["id"])
            if m["id"] == current_id:
                select_index = i
        self.main_window.available_onnx_models.setCurrentIndex(select_index)

    def update_progress(self, value):
        print(f"Progress update: {value}%")  # Debug print
        self.status_bar_progress.setValue(value)
        QtCore.QCoreApplication.processEvents()  # Process any pending events

    def change_tab(self, event=None):
        if self.main_window.graphical_2.isChecked():
            self.main_window.settings_options.setCurrentIndex(1)
        elif self.main_window.general_2.isChecked():
            self.main_window.settings_options.setCurrentIndex(0)
        elif self.main_window.misc_2.isChecked():
            self.main_window.settings_options.setCurrentIndex(3)
        elif self.main_window.voice_rec.isChecked():
            self.main_window.settings_options.setCurrentIndex(2)

    def delete_settings(self, event=None):
        self.settings_manager.clear_settings()

    def select_qss_path(self):
        qss_file_name, _ = QtWidgets.QFileDialog.getOpenFileName(self.main_window,
                                                                 "Open QSS StyleSheet",
                                                                 self.settings_manager.get_qss_file_path(),
                                                                 "QSS files (*.qss)")
        self.main_window.qss_path.setText(qss_file_name)

    def open_color_dialog(self, event=None):
        old_color = event.palette().button().color()
        new_color = QtWidgets.QColorDialog().getColor(old_color)
        new_text_color = "#ffffff" if new_color.lightnessF() < 0.5 else "#000000"
        style = "background-color: {};\n color: {};\n border: transparent;".format(new_color.name(), new_text_color)
        event.setStyleSheet(style)

    def open_app_data(self):
        qt_url = QtCore.QUrl.fromLocalFile(utilities.get_app_data_path().as_posix())
        QtGui.QDesktopServices.openUrl(qt_url)

    def load_settings_to_gui(self):
        # Use the settings manager to get values with proper type conversion
        self.main_window.fps_value.setValue(self.settings_manager.get_fps())
        self.main_window.run_voice_recognition.setChecked(self.settings_manager.get_run_voice_recognition())
        self.main_window.app_data_path.setText(utilities.get_app_data_path().as_posix())
        self.main_window.app_data_path.home(True)
        
        list_of_recognizers = ["ONNX"]
        self.main_window.selected_recognizer.addItems(list_of_recognizers)
        
        language_list = []
        for f in os.listdir(os.path.join(utilities.get_main_dir(), "rsrc", "i18n")):
            language_list.append(os.path.basename(f).split(".")[0])
        self.main_window.ui_language.addItems(language_list)
        
        lang_index = self.main_window.ui_language.findText(self.settings_manager.get_language())
        self.main_window.ui_language.setCurrentIndex(lang_index)
        
        self.main_window.rest_after_words.setChecked(self.settings_manager.get_rest_after_words())
        self.main_window.rest_after_phonemes.setChecked(self.settings_manager.get_rest_after_phonemes())
        
        recog_index = self.main_window.selected_recognizer.findText(self.settings_manager.get_recognizer())
        self.main_window.selected_recognizer.setCurrentIndex(recog_index)
        
        self.main_window.distribution_mode.setCurrentText(
            self.settings_manager.get_distribution_mode().capitalize())
        
        for color_button in self.main_window.graphical.findChildren(QtWidgets.QPushButton):
            if "Color" in color_button.text():
                new_color = QtGui.QColor(self.settings_manager.get_color(color_button.objectName()))
                new_text_color = "#ffffff" if new_color.lightnessF() < 0.5 else "#000000"
                style = "background-color: {};\n color: {};\n border: transparent;".format(new_color.name(),
                                                                                           new_text_color)
                color_button.setStyleSheet(style)
        
        # List available ONNX models via the backend's REST API.
        # Models that are already downloaded are marked with a checkmark.
        try:
            from backend_recognizer import BackendRecognizer
            recognizer = BackendRecognizer()
            models = recognizer.list_models("phoneme")
            onnx_model_list = []
            for m in models:
                mark = "[v] " if m["downloaded"] else "[ ] "
                onnx_model_list.append(mark + m["id"])
            # Store the raw model list for later use (download button, etc.)
            self._onnx_models = models
        except Exception as e:
            print(f"Could not list ONNX models from backend: {e}")
            onnx_model_list = []
            self._onnx_models = []
        self.main_window.available_onnx_models.addItems(onnx_model_list)

        # Select the currently configured model (match by id, ignoring the mark).
        current_model = self.settings_manager.get_onnx_model()
        for i in range(self.main_window.available_onnx_models.count()):
            item_text = self.main_window.available_onnx_models.itemText(i)
            if item_text.endswith(current_model):
                self.main_window.available_onnx_models.setCurrentIndex(i)
                break
        self.main_window.qss_path.setText(self.settings_manager.get_qss_file_path())

    def init_ui(self):
        self.translator = utilities.ApplicationTranslator()
        #self.app = QtCore.QCoreApplication.instance()
        #self.translator = QtCore.QTranslator()
        #self.translator.load("en_text", utilities.get_main_dir())
        self.main_window.general_2.clicked.connect(self.change_tab)
        self.main_window.graphical_2.clicked.connect(self.change_tab)
        self.main_window.misc_2.clicked.connect(self.change_tab)
        self.main_window.voice_rec.clicked.connect(self.change_tab)
        self.main_window.delete_settings.clicked.connect(self.delete_settings)
        self.main_window.reset_colors.clicked.connect(self.on_reset_colors)
        self.main_window.download_onnx_model.clicked.connect(self.download_onnx_model)
        self.main_window.accepted.connect(self.accepted)
        for color_button in self.main_window.graphical.findChildren(QtWidgets.QPushButton):
            if "Color" in color_button.text():
                self.main_window.connect(color_button, QtCore.SIGNAL("clicked()"),
                                         partial(self.open_color_dialog, color_button))
        self.load_settings_to_gui()
        self.main_window.open_app_data_path.clicked.connect(self.open_app_data)
        self.main_window.set_qss_path_button.clicked.connect(self.select_qss_path)
        self.main_window.settings_options.setCurrentIndex(0)
        # self.main_window.setWindowIcon(QtGui.QIcon(os.path.join(get_main_dir(), "rsrc", "window_icon.bmp")))
        # self.main_window.about_ok_button.clicked.connect(self.close)

    def on_reset_colors(self):
        self.settings_manager.reset_colors()
        for color_button in self.main_window.graphical.findChildren(QtWidgets.QPushButton):
            if "Color" in color_button.text():
                new_color = QtGui.QColor(self.settings_manager.get_color(color_button.objectName()))
                new_text_color = "#ffffff" if new_color.lightnessF() < 0.5 else "#000000"
                style = "background-color: {};\n color: {};\n border: transparent;".format(new_color.name(),
                                                                                           new_text_color)
                color_button.setStyleSheet(style)

    def accepted(self, event=None):
        # Save all settings using the settings manager
        self.settings_manager.set_fps(self.main_window.fps_value.value())
        self.settings_manager.set_run_voice_recognition(self.main_window.run_voice_recognition.isChecked())
        self.settings_manager.set_distribution_mode(self.main_window.distribution_mode.currentText().lower())
        self.settings_manager.set_qss_file_path(self.main_window.qss_path.text())
        self.settings_manager.set_recognizer(self.main_window.selected_recognizer.currentText())
        self.settings_manager.set_rest_after_words(self.main_window.rest_after_words.isChecked())
        self.settings_manager.set_rest_after_phonemes(self.main_window.rest_after_phonemes.isChecked())
        self.settings_manager.set_language(self.main_window.ui_language.currentText())
        # Strip the download-status mark from the model name before saving.
        onnx_model_text = self.main_window.available_onnx_models.currentText()
        onnx_model_id = onnx_model_text.replace("[v] ", "").replace("[ ] ", "")
        self.settings_manager.set_onnx_model(onnx_model_id)
        
        for color_button in self.main_window.graphical.findChildren(QtWidgets.QPushButton):
            if "Color" in color_button.text():
                self.settings_manager.set_color(color_button.objectName(), 
                                               color_button.palette().button().color().name())

    def close(self):
        if self.download_thread and self.download_thread.isRunning():
            print("Stopping download thread...")  # Debug print
            self.download_thread.stop()
            if not self.download_thread.wait(5000):  # Wait up to 5 seconds
                print("Force terminating download thread...")  # Debug print
                self.download_thread.terminate()
                self.download_thread.wait()
        self.main_window.close()
# end of class AboutBox
